name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: mehdiamiri1440
          output: gif
          color_snake: orange
          color_dots: #bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
